---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/*
- db/
- features/
- script/
- spec/
- vendor/
- app/controllers/application_controller.rb
- app/helpers/application_helper.rb	
- app/helpers/comments_helper.rb
- app/helpers/post_helper.rb
- app/helpers/registration_helper.rb
- app/helpers/taggedcomments_helper.rb
- app/helpers/welcome_helper.rb
JavaScript: true
Ruby: true
Python: false
PHP: false